name: Automated Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Unit Tests (PHP ${{ matrix.php }})
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: vendor
        key: vendor-${{ hashFiles('composer.json') }}
    - uses: php-actions/composer@v6
    - uses: php-actions/phpunit@v3
      with:
        version: 10
        php_version: ${{ matrix.php }}
        php_extensions: xdebug
        coverage_text: true
        bootstrap: vendor/autoload.php
        args: --coverage-filter src tests
      env:
        XDEBUG_MODE: coverage

  static:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: vendor
        key: vendor-${{ hashFiles('composer.json') }}
    - uses: php-actions/composer@v6
    - uses: php-actions/phpstan@v3
      with:
        path: src
        level: 9

  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: vendor
        key: vendor-${{ hashFiles('composer.json') }}
    - uses: php-actions/composer@v6
    - run: ./vendor/bin/php-cs-fixer fix && git diff --exit-code

