name: Automated Tests

on: [push, pull_request]

jobs:
  tests:
    name: Unit Tests (PHP${{ matrix.php-versions }})
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: php-actions/phpunit@v3
      with:
        php_version: ${{ matrix.php-versions }}
        args: tests

  static:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: php-actions/phpstan@v3
      with:
        path: src

  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - run: ./vendor/bin/php-cs-fixer fix && git diff --exit-code

